@startuml
'https://plantuml.com/state-diagram

TitleScreen -> WaveSelectScreen : Select NewGame

WaveSelectScreen -> WaveSelectScreen : \n Increase/decrease number of waves
WaveSelectScreen -down-> DifficultySelectScreen : Select 'Go'
WaveSelectScreen -> TitleScreen : Exit to Menu

DifficultySelectScreen -down-> GameScreen : Start game with 'Go'
DifficultySelectScreen -> DifficultySelectScreen : Choose difficulty
DifficultySelectScreen -> WaveSelectScreen : Select 'Back'

GameScreen -up-> Pause : Pause game with 'Settings' button
GameScreen -down-> Shop : Select 'Shop'

Pause -down-> GameScreen : Resume game
Pause -> AudioSettings : Select 'Audio'
Pause -> TitleScreen : Exit to Menu

AudioSettings -> AudioSettings : Change volume sliders
AudioSettings -up-> TitleScreen : Exit to Menu

Shop -> Shop : Buy station/chef
Shop -> GameScreen : Resume gane

state DifficultySelectScreen{
}

state GameScreen{
}

state Pause{
}

state TitleScreen{
}

state AudioSettings{
}

state Shop{
}

@enduml