@startuml
'https://plantuml.com/class-diagram

package "powerup"{

PowerupController "1" -- "*" Powerup

+class GetBeaned extends Powerup{
-GameScreen gameScreen
+GetBeaned(x:int, y:int, gameScreen:GameScreen)
+void applyPowerUp(cook:Cook)
}

+class Powerup{
-int x
-int y
~Texture texture
+boolean active
-int size
+Powerup(x:int, y:int)
+void draw(batch:SpriteBatch)
~Rectangle getCollideBox()
+void checkCollision(cook:Cook)
+void activate()
+void applyPowerup(cook:Cook)
}

+class PowerupController{
~ArrayList<Powerup> powerups
-long timeOfLast
-int selectIndex
+PowerupController(gameScreen:GameScreen)
+void updatePowerups(batch:SpriteBatch, cook:Cook)
}

+class Reputation extends Powerup{
-GameScreen gameScreen
+Reputation(x:int, y:int, gameScreen:GameScreen)
+void applyPowerUp(cook:Cook)
}

+class SpeedBoost extends Powerup{
+SpeedBoost(x:int, y:int)
+void applyPowerUp(cook:Cook)
}

}

@enduml